### ISSUE TITLE
Possible vulnerability issue in AAI Guideline

### ISSUE THREAD

**Issue by jaakkocsc** [elixir-cloud-aai/elixir-aai-guidelines#3]
Regarding AAI Guideline, if you hand out the same token to WES, TES and DRS, then by using such token a malicious TES is able to launch new workflows in WES and a malicious DRS is able to launch new tasks in TES. We do not want that. Tokens should always contain only the strictly required scopes.

**Comment by mikael-linden** [comment]
That can be tackled by the portal requesting 3 access tokens from the Authorisation server
- one with WES1_execute that is consumed by WES
- one with TES2_execute that is relayed by WES to TES that consumes it
- one with DRS3_read that is relayed by WES and TES to DRS that consumes it

It makes the user experience slightly worse; the user is presented three dialogues in a row and s/he needs to approve them all.

**Comment by mikael-linden** [comment]
Merged PR4 fixing the issue
